### PR TITLE
Tinybasetweaks

### PR DESCRIPTION
**Pull request by freehij**
e

### CODE REVIEW

**Comment by freehij** [comment]
thanku buddy 🥰

**Comment by GameHerobrine** [comment]
> thanku buddy 🥰

not even testing this thing oof

**Comment by freehij** [comment]
> > thanku buddy 🥰
> 
> not even testing this thing oof

i believe gameherobrine is a good coder

**Comment by GameHerobrine** [comment]
i believe skibidiwaredev was the best coder when he made shid

> > > thanku buddy 🥰
> > 
> > 
> > not even testing this thing oof
> 
> i believe gameherobrine is a good coder

**Pull request merged**
